### ISSUE TITLE
help with deploying streamlit app?

### ISSUE THREAD

**Issue by vivianyoung** [CMU-IDS-2021/fp--virol-vivian-carol#1]
We would like our app to be deployed as a Streamlit app like in Assignment 2. Could we get help with this?

**Comment by kai-qu** [comment]
Is there a main file for the app? I tried with app_carol.py and it threw an error. https://share.streamlit.io/cmu-ids-2021/fp--virol-vivian-carol/main/app_carol.py

**Comment by kai-qu** [comment]
```
client] Connecting...

[manager] Starting up for owner: 'cmu-ids-2021', repository: 'fp--virol-vivian-carol', branch: 'main', main module: 'app_carol.py'

[manager] Cloning repository ...

[manager] Cloning into 'fp--virol-vivian-carol'...

[manager] Cloned repository!

[manager] Processing dependencies ...

[manager] Processed dependencies!

2021-05-06 20:46:30.228 An update to the [server] config option section was detected. To have these changes be reflected, please restart streamlit.

2021-05-06 20:46:30.314 Uncaught app exception

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/script_runner.py", line 337, in _run_script

    exec(code, module.__dict__)

  File "/app/fp--virol-vivian-carol/app_carol.py", line 5, in <module>

    import plotly.express as px

ModuleNotFoundError: No module named 'plotly'




2021-05-06 20:46:48.459 Uncaught app exception

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/script_runner.py", line 337, in _run_script

    exec(code, module.__dict__)

  File "/app/fp--virol-vivian-carol/app_carol.py", line 5, in <module>

    import plotly.express as px

ModuleNotFoundError: No module named 'plotly'
```

**Comment by vivianyoung** [comment]
Sorry! I just removed the unused module. Could you try again?

**Comment by kai-qu** [comment]
You will need to remove the module everywhere, e.g. utils.py. Streamlit should auto-update when you push to main.

```
2021-05-07 17:23:12.683 Uncaught app exception

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/script_runner.py", line 337, in _run_script

    exec(code, module.__dict__)

  File "/app/fp--virol-vivian-carol/app_carol.py", line 6, in <module>

    from utils import *

  File "/app/fp--virol-vivian-carol/utils.py", line 5, in <module>

    import plotly.express as px

ModuleNotFoundError: No module named 'plotly'
```

**Comment by dondendon** [comment]
removed and it deployed successfully, thank you!

**Comment by kai-qu** [comment]
Great!
